---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ postgresql_apt_dependencies }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Create keyring directory
  ansible.builtin.file:
    path: "{{ postgresql_apt_keyring_file_path | dirname }}"
    state: directory
    mode: "0755"

- name: Download repository key
  ansible.builtin.get_url:
    url: "{{ postgresql_apt_repo_key_url }}"
    dest: "{{ postgresql_apt_keyring_file_path }}"
    mode: "0644"

# Gets the proper codename even when running on Ubuntu based (e.g. Linux Mint)
- name: Gets distro codename
  ansible.builtin.shell:
    cmd: . /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"
  changed_when: false
  register: postgresql_distro_codename

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "{{ postgresql_apt_repo_string }}"
    state: present
    update_cache: true

- name: Install postgresql
  ansible.builtin.apt:
    name: "{{ postgresql_apt_install_pkgs }}"
    state: present
  notify: Restart postgresql
