---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Update dnf cache
  ansible.builtin.dnf:
    update_cache: true

- name: Reset ssh connection
  ansible.builtin.meta: reset_connection

- name: Restart docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted
