name: CI
on:
  # trunk-ignore(yamllint/empty-values)
  pull_request:
  push:
    branches: [main]

permissions: read-all

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4
      
      - name: List Ansible roles
        id: set-matrix
        run: |
          # Gather role directory names
          roles_json=$(find roles -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | jq -R . | jq -s .)
          # Build a compact JSON matrix
          matrix=$(jq -c -n --argjson rs "$roles_json" '{role: $rs}')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      # Fails without "requirements.txt" for some reason
      # https://github.com/marketplace/actions/build-and-setup-python#no-file-in--matched-to-requirementstxt-or-pyprojecttoml-make-sure-you-have-checked-out-the-target-repository
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Run Molecule tests
        run: cd roles/${{ matrix.role }}/ && molecule test
        env:
          # Enable colors in CI logs
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
