---
dependencies: []

galaxy_info:
  role_name: docker
  author: gustavoav
  description: Docker for Linux
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Rocky
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - web
    - system
    - containers
    - docker
    - orchestration
    - compose
    - server
